export const REGISTRATION_SUCCESSFUL = "REGISTRATION_SUCCESSFUL";
export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
